name: Update the Spring website project page for new version

description: 'Update the Spring website project page for new version. The SNAPSHOT version is also added if generation permits. Supports only Antora docs.'

inputs:
  newVersion:
    description: 'The version to add to project page'
    required: true
  token:
    description: 'A GitHub token for REST api calls'
    required: true

runs:
  using: composite
  steps:
    - name: Update project page for new version
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        set -euo pipefail

        PROJECT=${{ github.event.repository.name }}
        GITHUB_USER=$(gh api /user --jq '.login')
        
        # Check if project exists on Spring website
        HTTP_CODE=$(curl -s -u "$GITHUB_USER:$GH_TOKEN" \
                      -H "Content-Type: application/json" \
                      -o /dev/null -w '%{http_code}' \
                      "https://api.spring.io/projects/$PROJECT")
        
        if [ "$HTTP_CODE" != "200" ]
        then
           echo "::notice title=Nothing to update on Spring website::No versions update for $PROJECT project which is not listed on Spring website."
           exit 0
        fi
        
        VERSIONS_TO_UPDATE=${{ inputs.newVersion }}
       
        MAJOR_MINOR=$(echo ${{ inputs.newVersion }} | cut -d '.' -f1-2)
        
        # Fetch OSS support end date
        OSS_SUPPORT_END_DATE=$(curl -s -u "$GITHUB_USER:$GH_TOKEN" \
                                  -H "Content-Type: application/json" \
                                  "https://api.spring.io/projects/$PROJECT/generations/${MAJOR_MINOR}.x" | \
                      jq -r '.ossSupportEndDate // empty')
        
        # Add next SNAPSHOT version if OSS support is still active
        if [[ -n "$OSS_SUPPORT_END_DATE" && "$OSS_SUPPORT_END_DATE" > "$(date '+%F')" ]]
        then
          NEXT_SNAPSHOT=${{ inputs.newVersion }}
        
          if [[ $NEXT_SNAPSHOT == *"-"* ]] 
          then
            NEXT_SNAPSHOT=${NEXT_SNAPSHOT/-*}
          else
            PATCH=$(echo $NEXT_SNAPSHOT | cut -d '.' -f3)
            PATCH=$((PATCH+1))
            NEXT_SNAPSHOT=$MAJOR_MINOR.$PATCH
          fi
        
          NEXT_SNAPSHOT+='-SNAPSHOT'
          VERSIONS_TO_UPDATE+=" $NEXT_SNAPSHOT"
        fi
        
        # Fetch versions to remove
        VERSIONS_TO_REMOVE=$(curl -s -u "$GITHUB_USER:$GH_TOKEN" \
                                -H "Content-Type: application/json" \
                                "https://api.spring.io/projects/$PROJECT/releases" | \
                          jq -r "._embedded.releases[].version | select(startswith(\"$MAJOR_MINOR\"))")
        
        # Remove old versions
        for VERSION_TO_REMOVE in $VERSIONS_TO_REMOVE
        do
           echo "Removing version: $VERSION_TO_REMOVE"

           curl -s -u "$GITHUB_USER:$GH_TOKEN" \
              -H "Content-Type: application/json" \
              -X DELETE \
              --fail --show-error \
              "https://api.spring.io/projects/$PROJECT/releases/$VERSION_TO_REMOVE"
        done
        
#        sleep 1
        
        # Add new versions
        for VERSION in $VERSIONS_TO_UPDATE
        do
            echo "Adding version: $VERSION"
 
            VERSION_JSON=$(jq -n \
             --arg version "$VERSION" \
             --arg project "$PROJECT" \
             '{version: $version, referenceDocUrl: "https://docs.spring.io/\($project)/reference/{version}", apiDocUrl: "https://docs.spring.io/\($project)/docs/\($version)/api", isAntora: true}')
        
            curl -s -u "$GITHUB_USER:$GH_TOKEN" \
              -H "Content-Type: application/json" \
              -d "$VERSION_JSON" \
              --fail --show-error \
              "https://api.spring.io/projects/$PROJECT/releases"
        done