name: Deploy Release (Milestone or GA) to Maven Central from Artifactory Build

on:
  workflow_call:
    inputs:
      buildName:
        description: 'The Artifactory Build Name'
        required: true
        type: string
      buildNumber:
        description: 'The Artifactory Build Number'
        required: true
        type: string

    secrets:
      CENTRAL_TOKEN_USERNAME:
        required: true
      CENTRAL_TOKEN_PASSWORD:
        required: true
      JF_ARTIFACTORY_SPRING:
        required: true

env:
  JF_ENV_SPRING: ${{ secrets.JF_ARTIFACTORY_SPRING }}
  WORKFLOWS_REF: main

jobs:
  deploy-to-maven-central:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v6
        with:
          repository: spring-io/spring-github-workflows
          show-progress: false
          ref: ${{ env.WORKFLOWS_REF }}

      - uses: jfrog/setup-jfrog-cli@v5

      - name: Download Release Files
        run: |
          jfrog rt download \
            --spec utils/release-files-spec.json \
            --spec-vars "buildname=${{ inputs.buildName }};buildnumber=${{ inputs.buildNumber }}"

      - name: Deploy Bundle to Maven Central Portal
        uses: spring-io/central-publish-action@v0.4.0
        with:
          token-name: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          token: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
          dir: central_bundle
          ignore-already-exists-error: true
