name: Find Current Version to Release

on:
  workflow_call:
    outputs:
      releaseVersion:
        description: Current Milestone to release
        value: ${{ jobs.find-release-version.outputs.releaseVersion }}

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  find-release-version:
    runs-on: ubuntu-latest
    outputs:
      releaseVersion: ${{ steps.find-milestone.outputs.milestone }}

    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Checkout Common Repo
        uses: actions/checkout@v4
        with:
          repository: spring-io/spring-github-workflows
          path: .github/spring-github-workflows
          show-progress: false
          ref: ${{ env.WORKFLOWS_REF }}

      - name: Find Scheduled Milestone
        id: find-milestone
        uses: ./.github/spring-github-workflows/.github/actions/spring-scheduled-milestone-for-branch

      - name: Version to Release
        run: |
          RELEASE_VERSION=${{ steps.find-milestone.outputs.milestone }}
          if [ -z $RELEASE_VERSION ]
          then
            gh run cancel ${{ github.run_id }}
            echo "::warning title=Nothing to release::No scheduled milestone for ${{ steps.find-milestone.outputs.currentVersion }} version"
          else
            echo "::notice title=RELEASE VERSION::$RELEASE_VERSION"
          fi