name: Distribute Spring Enterprise Release Bundle

# Intended to be used in private repositories for commercial releases where an allowed ubuntu22-2-8 GH runner is available

on:
  workflow_call:

    inputs:
      artifactoryUrl:
        description: 'The Artifactory Server'
        required: true
        type: string
      bundleName:
        description: 'The Artifactory Bundle Name'
        required: true
        type: string
      releaseVersion:
        description: 'The Bundle Version (usually project release)'
        required: true
        type: string
      buildName:
        description: 'The Artifactory Build Name'
        required: true
        type: string
      buildNumber:
        description: 'The Artifactory Build Number'
        required: true
        type: string

    secrets:
      ARTIFACTORY_USERNAME:
        required: true
      ARTIFACTORY_PASSWORD:
        required: true

jobs:
  distribute-spring-enterprise-release-bundle:
    runs-on: ubuntu22-2-8
    steps:
      - uses: spring-io/spring-release-actions/distribute-release-bundle@0.0.4
        with:
          artifactory-url: ${{ inputs.artifactoryUrl }}
          bundle-name: ${{ inputs.bundleName }}
          build-name: ${{ inputs.buildName }}
          build-number: ${{ inputs.buildNumber }}
          version: ${{ inputs.releaseVersion }}
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}
