name: Automatically cherry-pick commit

on:
  workflow_call:
    inputs:
      autoCherryPickToken:
        description: 'The sub-string in the commit message to determine that commit has to be cherry-picked'
        required: false
        default: Auto-cherry-pick to
        type: string

    secrets:
      GH_ACTIONS_REPO_TOKEN:
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_REPO_TOKEN }}


jobs:
  cherry-pick:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, inputs.autoCherryPickToken)
    steps:

      - uses: actions/checkout@v4
        with:
          token: ${{ env.GITHUB_TOKEN }}
          show-progress: false
          fetch-depth: 0

      - name: Cherry-pick to branches in commit message
        env:
          CHERRY_PICK_TOKEN: ${{ inputs.autoCherryPickToken }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          git config --global user.name 'Spring Builds'
          git config --global user.email 'builds@springframework.org'
          branches=$(echo "$COMMIT_MESSAGE" | grep "$CHERRY_PICK_TOKEN" | grep -o1 -E "([0-9]+\.[0-9]+\.x)")
          for branch in $branches
          do 
            if [ "$branch" != '${{ github.ref_name }}' ]
            then
              git checkout "$branch"
              if git cherry-pick ${{ github.sha }} -x
              then
                echo "::notice title=Commit cherry-picked::${{ github.sha }} to branch $branch"
              else
                echo "::error title=Cannot cherry-pick::${{ github.sha }} to branch $branch. Manual procedure required"
                exit 1
              fi
              branchCommitMessage=$(git log -1 --pretty=%B | grep -v "$CHERRY_PICK_TOKEN")
              git commit --amend -o -m "$branchCommitMessage"  
              git push origin $branch    
            fi
          done
