name: Deploy Release (Milestone or GA) to Maven Central from Artifactory Build

on:
  workflow_call:
    inputs:
      buildName:
        description: 'The Artifactory Build Name'
        required: true
        type: string
      buildNumber:
        description: 'The Artifactory Build Number'
        required: true
        type: string

    secrets:
      CENTRAL_TOKEN_USERNAME:
        required: true
      CENTRAL_TOKEN_PASSWORD:
        required: true
      JF_ARTIFACTORY_SPRING:
        required: true

env:
  JF_ENV_SPRING: ${{ secrets.JF_ARTIFACTORY_SPRING }}

jobs:
  deploy-to-maven-central:
    runs-on: ubuntu-latest
    steps:

      - uses: jfrog/setup-jfrog-cli@v5

      - name: Download Release Files
        run: |
          cat << 'EOF' > release-files-spec.json
          {
            "files": [
              {
                "aql": {
                  "items.find": {
                    "$and": [
                      {
                        "@build.name": "${{ inputs.buildName }}",
                        "@build.number": "${{ inputs.buildNumber }}",
                        "path": {
                          "$match": "org/springframework*"
                        }
                      },
                      {
                        "$or": [
                          { "name": { "$match": "*.pom" } },
                          { "name": { "$match": "*.jar" } },
                          { "name": { "$match": "*.module" } },
                          { "name": { "$match": "*.asc" } }
                        ]
                      },
                      {
                        "name": { "$nmatch": "*.zip.asc" }
                      }
                    ]
                  }
                },
                "target": "central_bundle/"
              }
            ]
          }
          EOF
          
          jfrog rt download --spec release-files-spec.json 

      - name: Deploy Bundle to Maven Central Portal
        uses: spring-io/central-publish-action@v0.4.0
        with:
          token-name: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          token: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
          dir: central_bundle
          ignore-already-exists-error: true
