name: Perform Post Release Procedures

on:
  workflow_call:
    inputs:
      milestone:
        description: 'Milestone title, e.g 3.0.0-M1, 3.1.0-RC1, 3.2.0 etc.'
        required: true
        type: string

    secrets:
      SPRING_RELEASE_CHAT_WEBHOOK_URL:
        required: false
      GH_ACTIONS_REPO_TOKEN:
        required: true

env:
  WORKFLOWS_REF: main
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


jobs:
  post-release:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v6
        with:
          show-progress: false

      - name: Checkout Common Repo
        uses: actions/checkout@v6
        with:
          repository: spring-io/spring-github-workflows
          path: .github/spring-github-workflows
          show-progress: false
          ref: ${{ env.WORKFLOWS_REF }}

      - name: Update Spring IO website for new version
        uses: ./.github/spring-github-workflows/.github/actions/spring-website-project-version-update
        with:
          newVersion: ${{ inputs.milestone }}
          token: ${{ secrets.GH_ACTIONS_REPO_TOKEN }}

      - name: Announce Release in Chat
        if: env.CHAT_WEBHOOK_URL
        uses: spring-io/spring-release-actions/announce-on-gchat@0.0.4
        with:
          gchat-webhook-url: ${{ env.CHAT_WEBHOOK_URL }}
          version: ${{ inputs.milestone }}
        env:
          CHAT_WEBHOOK_URL: ${{ secrets.SPRING_RELEASE_CHAT_WEBHOOK_URL }}

      - id: support-window
        if: ${{ !contains(inputs.milestone, '-') }}
        uses: spring-io/spring-release-actions/compute-support-window@main

      - id: next-milestone
        if: ${{ steps.support-window.outputs.support-type != 'eol' }}
        uses: spring-io/spring-release-actions/compute-next-version@0.0.4
        with:
          version: ${{ inputs.milestone }}

      - name: Schedule Milestone
        if: steps.next-milestone.outputs.milestone
        uses: spring-io/spring-release-actions/schedule-milestone@0.0.4
        with:
          version-date: ${{ steps.next-milestone-date.outputs.due-date }}
          version: ${{ steps.next-milestone.outputs.milestone }}