name: Find Current Version to Release

on:
  workflow_call:
    outputs:
      releaseVersion:
        description: Current Milestone to release
        value: ${{ jobs.find-release-version.outputs.releaseVersion }}

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  find-release-version:
    runs-on: ubuntu-latest
    outputs:
      releaseVersion: ${{ steps.milestone.outputs.release-version }}

    steps:
      - uses: actions/checkout@v6
        with:
          show-progress: false

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Compute Version
        id: compute-version
        uses: spring-io/spring-release-actions/compute-version@0.0.4

      - name: Compute next scheduled milestone
        id: milestone
        uses: spring-io/spring-release-actions/compute-next-scheduled-milestone@0.0.4
        with:
          snapshot-version: ${{ steps.compute-version.outputs.version }}

      - name: Version to Release
        run: |
          RELEASE_VERSION=${{ steps.milestone.outputs.release-version }}
          if [ -z $RELEASE_VERSION ]
          then
            gh run cancel ${{ github.run_id }}
            echo "::warning title=Nothing to release::No scheduled milestone for ${{ steps.compute-version.outputs.version }} version"
          else
            echo "::notice title=RELEASE VERSION::$RELEASE_VERSION"
          fi