name: CI Artifactory Build for Gradle

on:
  workflow_call:
    inputs:
      releaseVersion:
        description: 'Release version like 3.0.0-M1, 3.1.0-RC1, 3.2.0 etc. If not specified this workflow acts as a SNAPSHOT build.'
        required: false
        type: string
      gradleTasks:
        description: 'Additional Gradle tasks. The `build` and `publishAllPublicationsToDeploymentRepository` are included.'
        required: false
        type: string
      artifactoryUrl:
        description: 'The Artifactory Server'
        required: false
        type: string
      targetRepository:
        description: 'The Artifactory Repository to upload artifacts to'
        required: false
        type: string
      artifactoryProjectKey:
        description: 'The Artifactory project key'
        required: false
        type: string
      runner:
        description: 'The runner for job'
        required: false
        type: string
        default: ubuntu-latest

    outputs:
      buildName:
        description: 'Artifactory Build Name'
        value: ${{ jobs.build-with-gradle.outputs.buildName }}
      buildNumber:
        description: 'Artifactory Build Number'
        value: ${{ jobs.build-with-gradle.outputs.buildNumber }}

    secrets:
      DEVELOCITY_ACCESS_KEY:
        required: false
      ARTIFACTORY_USERNAME:
        required: true
      ARTIFACTORY_PASSWORD:
        required: true
      GPG_PASSPHRASE:
        required: false
      GPG_PRIVATE_KEY:
        required: false

env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
  WORKFLOWS_REF: main

jobs:
  build-with-gradle:
    runs-on: ${{ inputs.runner }}
    name: CI Build for ${{ github.ref_name }}

    outputs:
      buildName: ${{ steps.build-and-publish.outputs.buildName }}
      buildNumber: ${{ steps.build-and-publish.outputs.buildNumber }}

    steps:

      - uses: actions/checkout@v5
        with:
          show-progress: false

      - name: Checkout Common Repo
        uses: actions/checkout@v5
        with:
          repository: spring-io/spring-github-workflows
          path: .github/spring-github-workflows
          show-progress: false
          ref: ${{ env.WORKFLOWS_REF }}

      - name: Build and Publish
        id: build-and-publish
        timeout-minutes: 30
        uses: ./.github/spring-github-workflows/.github/actions/spring-artifactory-gradle-build
        with:
          releaseVersion: ${{ inputs.releaseVersion }}
          gradleTasks: ${{ inputs.gradleTasks }}
          artifactoryUrl: ${{ inputs.artifactoryUrl }}
          targetRepository: ${{ inputs.targetRepository }}
          artifactoryProjectKey: ${{ inputs.artifactoryProjectKey }}
          artifactoryUsername: ${{ secrets.ARTIFACTORY_USERNAME }}
          artifactoryPassword: ${{ secrets.ARTIFACTORY_PASSWORD }}
          gpgPrivateKey: ${{ secrets.GPG_PRIVATE_KEY }}
          gpgPassphrase: ${{ secrets.GPG_PASSPHRASE }}


