name: Continuous Integration Build for Gradle

on:
  workflow_call:
    inputs:
      testJavaVersion:
        description: 'Java version for testing'
        required: true
        type: string
      gradleTasks:
        description: 'Additional Gradle tasks. The `build` is included'
        required: false
        type: string
      runner:
        description: 'The runner for job'
        required: false
        type: string
        default: ubuntu-latest

    secrets:
      DEVELOCITY_ACCESS_KEY:
        required: false
      ARTIFACTORY_USERNAME:
        required: false
      ARTIFACTORY_PASSWORD:
        required: false

env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

jobs:
  ci-with-gradle:
    name: CI for ${{ github.ref_name }} with Java ${{ inputs.testJavaVersion }} on ${{ inputs.runner }}
    runs-on: ${{ inputs.runner }}

    steps:

      - uses: actions/checkout@v6
        with:
          show-progress: false

      - name: Set up Gradle
        uses: spring-io/spring-gradle-build-action@v2
        with:
          java-version: 25

      - name: CI Build
        shell: bash
        run: |
          echo CI Build
          
          ./gradlew check ${{ inputs.gradleTasks }} -PtestJavaVersion=${{ inputs.testJavaVersion }}
        env:
          ARTIFACTORY_USERNAME: ${{ inputs.artifactoryUsername }}
          ARTIFACTORY_PASSWORD: ${{ inputs.artifactoryPassword }}

